name: Deploy to OSS

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - .github

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GENERATE_SOURCEMAP: false

    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --network-timeout=1000000 # will run `yarn install` command

      - uses: borales/actions-yarn@v2.3.0
        env:
          CI: false
        with:
          cmd: build # will run `yarn build` command

      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.OSS_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          bucket: "banksy-finance-exchange"
          # use your own endpoint
          endpoint: "oss-cn-hongkong.aliyuncs.com"
          folder: "build"
          skipSetting: true
