name: Deploy site files

on:
  push:
    branches:
      - v1
      - 'dev/**'
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GENERATE_SOURCEMAP: false

    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command

      - uses: borales/actions-yarn@v2.3.0
        env:
          CI: false
        with:
          cmd: build # will run `yarn build` command

      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: -avz --delete
          SERVER_PORT: "22"
          FOLDER: ./build/ # Folder to push. The path is relative to the root directory of the code repository
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          SERVER_DESTINATION: /home/devops/banksea_website/middleware/ui/app-testnet

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: | # Script to restart, according to their own situation to change the corresponding,
            docker-compose -f /home/devops/banksea_website/middleware/docker-compose.yml restart banksea_website_nginx
